name: test
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install Dependencies
      run: npm ci

    - name: Test App
      run: npm test

  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
         Username: frankisinfotech
         Password: ${}
         
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependency
      run: npm ci

    - name: Build App
      run: npm run build

    - name: Deploy app
      run: echo "Deploying....."
