name: test
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install Dependencies
      run: npm ci

    - name: Test App
      run: npm test

  buildtoDHub:
    needs: testing
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
         Username: frankisinfotech
         Password: ${{ secrets.PASSWORD }}
    
    - name: Build and Push Image
      run: |
           docker build -t reactimg .
           docker tag reactimg frankisinfotech/cohort-3:v1
           docker push frankisinfotech/cohort-3:v1
      
  buildtoAWS:
    needs: buildtoDHub
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: AWS ECR Login
      uses: elgohr/ecr-login-action@v3
      with:
         access_key: ${{ secrets.ACCESS_KEY }}
         secret_access_key: ${{ secrets.SECRET_KEY }}
         
  deploy:
    needs: buildtoAWS
    runs-on: ubuntu-latest
    steps:
      
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependency
      run: npm ci

    - name: Build App
      run: npm run build

    - name: Deploy app
      run: echo "Deploying....."
